version: "3.3"
services:
  nginx:
    image: nginx
    working_dir: /
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    healthcheck:
      test: curl -I ${HEALTHCHECK_URL}
      interval: 30s
      timeout: 10s
      retries: 2
  php-fpm:
    build: docker/php
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    ports:
    - 3307:3306
#    volumes:
#      - .docker/data/db:/var/lib/mysql
    environment:
#      MYSQL_DATABASE: mysql
#      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}